name = "mi-pagina-web"
compatibility_date = "2024-09-25"
main = "worker/index.js"

[[d1_databases]]
binding = "DB"
database_name = "ellel-db"
database_id = "e204fb51bbefb45d71927bb1cda8fb7f"

[assets]
directory = "./public"